apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: alef-backend
  labels:
    app: database
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: database
